language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk7
  - openjdk8
dist: trusty
sudo: false

script: mvn test

after_success:
  - mvn clean jacoco:prepare-agent install jacoco:report coveralls:report

cache:
  directories:
    - $HOME/.m2