language: java
jdk:
  - oraclejdk8
#  - oraclejdk9
#  - openjdk8
dist: trusty
sudo: false

script: mvn test

after_success:
  - mvn clean test jacoco:report coveralls:report

cache:
  directories:
    - $HOME/.m2